# Tache 5

Ludovic Delferiere 81232000

Import et téléchargement du fichier 

In [1]:
import numpy as np
from mp_api.client import MPRester
from pymatgen.core.operations import SymmOp
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pymatgen.electronic_structure.plotter import BSPlotter
from pymatgen.phonon.plotter import PhononBSPlotter
from jupyter_jsmol.pymatgen import quick_view
mp_key = "hWWmIDodjhkgKVHj88m318vKs3nGtcQp"
mp_id = "mp-1029"

In [2]:
with MPRester(mp_key) as m:
    #récupération de la structure 
    prim_struc = m.get_structure_by_material_id(mp_id)
    el_bs = m.get_bandstructure_by_material_id(mp_id)
    el_dos = m.get_dos_by_material_id(mp_id)
    ph_bs = m.get_phonon_bandstructure_by_material_id(mp_id)
    ph_dos = m.get_phonon_dos_by_material_id(mp_id)
conv_struc = SpacegroupAnalyzer(prim_struc).get_conventional_standard_structure() #conventionelle
symmops = SpacegroupAnalyzer(conv_struc).get_space_group_operations() #operations du groupe

Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving ElectronicStructureDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving ElectronicStructureDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving PhononBSDOSDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving PhononBSDOSDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

# Listage de toutes les opérations de symmétrie

In [3]:
print(symmops) #permet de connaitre le groupe spatial
analyse=SpacegroupAnalyzer(prim_struc)
print(analyse.get_symmetry_operations()) #permet d'avoir les opérations de symétrie 
listeofsym = analyse.get_symmetry_operations()


Fm-3m (225) spacegroup
[SymmOp(affine_matrix=array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])), SymmOp(affine_matrix=array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])), SymmOp(affine_matrix=array([[-1.,  0.,  0.,  0.],
       [ 0., -1.,  0.,  0.],
       [ 0.,  0., -1.,  0.],
       [ 0.,  0.,  0.,  1.]])), SymmOp(affine_matrix=array([[-1.,  0.,  0.,  0.],
       [ 0., -1.,  0.,  0.],
       [ 0.,  0., -1.,  0.],
       [ 0.,  0.,  0.,  1.]])), SymmOp(affine_matrix=array([[ 0., -1.,  0.,  0.],
       [ 1.,  1.,  1.,  0.],
       [-1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.]])), SymmOp(affine_matrix=array([[ 0., -1.,  0.,  0.],
       [ 1.,  1.,  1.,  0.],
       [-1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.]])), SymmOp(affine_matrix=array([[ 0.,  1.,  0.,  0.],
       [-1., -1., -1.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.]])), SymmOp(affine_matrix=array([

# Affichage des sites de la structure conventionelle

In [4]:
sites = conv_struc.sites  
print(sites)

[PeriodicSite: Ba (0.0, 0.0, 0.0) [0.0, 0.0, 0.0], PeriodicSite: Ba (5.006e-16, 3.113, 3.113) [0.0, 0.5, 0.5], PeriodicSite: Ba (3.113, 0.0, 3.113) [0.5, 0.0, 0.5], PeriodicSite: Ba (3.113, 3.113, 3.812e-16) [0.5, 0.5, 0.0], PeriodicSite: F (4.669, 1.556, 4.669) [0.75, 0.25, 0.75], PeriodicSite: F (4.669, 1.556, 1.556) [0.75, 0.25, 0.25], PeriodicSite: F (4.669, 4.669, 1.556) [0.75, 0.75, 0.25], PeriodicSite: F (4.669, 4.669, 4.669) [0.75, 0.75, 0.75], PeriodicSite: F (1.556, 1.556, 1.556) [0.25, 0.25, 0.25], PeriodicSite: F (1.556, 1.556, 4.669) [0.25, 0.25, 0.75], PeriodicSite: F (1.556, 4.669, 4.669) [0.25, 0.75, 0.75], PeriodicSite: F (1.556, 4.669, 1.556) [0.25, 0.75, 0.25]]


# Opérations de symmétrie 1 sur Ba

In [5]:
symm_1 = listeofsym[54]

print("Opération de symmétrie n°1:")
print("(x, y, z) -> (" + str(symm_1.as_xyz_str())+ ")")

print("\nMatrice de rotation:")
print(symm_1.rotation_matrix)

print("\nTranslation:")
print(symm_1.translation_vector)

Opération de symmétrie n°1:
(x, y, z) -> (z, y, x)

Matrice de rotation:
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]

Translation:
[0. 0. 0.]


In [6]:
print("Coordonnées Ba initial :")
positioninitiale_1 = [0.0, 0.0, 0.0]
print(positioninitiale_1)

print("\nCoordonnées Ba après opération :")

print(symm_1.operate(positioninitiale_1))
#on va choisir un autre Ba pour voir l'effet de la symétrie
print("Coordonnées d'un autre Ba situé en :")
positioninitiale_2 = [0.0,0.5,0.5]
print(positioninitiale_2)
print("\nCoordonnées Ba après opération :")
print(symm_1.operate(positioninitiale_2))



Coordonnées Ba initial :
[0.0, 0.0, 0.0]

Coordonnées Ba après opération :
[0. 0. 0.]
Coordonnées d'un autre Ba situé en :
[0.0, 0.5, 0.5]

Coordonnées Ba après opération :
[0.5 0.5 0. ]


In [7]:
view = quick_view(conv_struc)
display(view) 
view.script('draw symop 55 {atomno = 1}')

JsmolView(layout=Layout(align_self='stretch', height='400px'))

Il s'agit d'une symmétrie mirroir par rapport au plan xz (101)

# Opération de symmétrie 2 sur un F

In [8]:
symm_2 = listeofsym[52]

print("Opération de symmétrie n°2:")
print("(x, y, z) -> (" + str(symm_2.as_xyz_str())+ ")")

print("\nMatrice de Rotation:")
print(symm_2.rotation_matrix)

print("\nVecteur de translation:")
print(symm_2.translation_vector)

Opération de symmétrie n°2:
(x, y, z) -> (-z, -y, -x)

Matrice de Rotation:
[[ 0.  0. -1.]
 [ 0. -1.  0.]
 [-1.  0.  0.]]

Vecteur de translation:
[0. 0. 0.]


In [9]:
print("Coordonnées F avant symmétrie :")
positioninitiale_2 = [0.75, 0.25, 0.75]
print(positioninitiale_2)

print("\nCoordonnées F après opération :")

print(symm_2.operate(positioninitiale_2))

Coordonnées F avant symmétrie :
[0.75, 0.25, 0.75]

Coordonnées F après opération :
[-0.75 -0.25 -0.75]


In [10]:
view = quick_view(conv_struc)
display(view) 
view.script('draw symop 53 {atomno = 2}')

JsmolView(layout=Layout(align_self='stretch', height='400px'))

Il s'agit d'une opération de roto-inversion, cette opération combine une rotation avec une inversion (une réflexion par rapport à l'origine).

# Opérations de symmetrie 3 sur un Ba

In [11]:
symm_3 = listeofsym[80]
    
print("Opération de symmétrie n°3:")
print("(x, y, z) -> (" + str(symm_3.as_xyz_str())+ ")")

print("\nMatrice de Rotation:")
print(symm_3.rotation_matrix)

print("\nVecteur de translation:")
print(symm_3.translation_vector)

Opération de symmétrie n°3:
(x, y, z) -> (z, x, y)

Matrice de Rotation:
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]

Vecteur de translation:
[0. 0. 0.]


In [12]:
print("Coordonnées Ba avant symmétrie :")
positioninitiale_3 = [0.0, 0.5, 0.5]
print(positioninitiale_3)

print("\nCoordonnées Ba après opération :")

print(symm_3.operate(positioninitiale_3))

Coordonnées Ba avant symmétrie :
[0.0, 0.5, 0.5]

Coordonnées Ba après opération :
[0.5 0.  0.5]


In [13]:
view = quick_view(conv_struc)
display(view) 
view.script('draw symop 81 {atomno = 2}')

JsmolView(layout=Layout(align_self='stretch', height='400px'))

Il s'agit s'une rotation de 90° dans le sens horlogique, soit une rotation d'ordre 4.